"""Export PRISM output for sharing (PR-166.1, Part 3).

Three formats — Markdown, plain text and PDF — each carrying the same
provenance: which provider and model produced the text, from which
prompt VERSION, when, and what redaction removed before anything was
sent.

A PRISM view shared without its provenance is indistinguishable from a
human-written statement of fact. That is precisely the confusion the
whole platform exists to prevent, so provenance is not optional in any
format, and every export states plainly that Atlas — not the model —
determined the findings.

What is NEVER exported: API keys, endpoints, internal identifiers,
ledger entries, or any telemetry beyond the generation metadata shown
to the operator on screen.
"""

from __future__ import annotations

from typing import Any, Mapping


PROVENANCE_STATEMENT = (
    "Generated by PRISM, the Atlas Evidence Presentation Platform. "
    "Atlas determined the findings; PRISM only restated them for this "
    "audience. PRISM cannot add evidence, change a conclusion, or "
    "remove an uncertainty. The Atlas evidence this was generated from "
    "is reproduced above and remains the source of truth."
)

# Metadata an export may carry — an allowlist, so a future field added
# to a view cannot leak into a shared document by accident.
EXPORTED_FIELDS = (
    ("audience_label", "Audience"),
    ("language_label", "Language"),
    ("capability", "Capability"),
    ("provider", "Provider"),
    ("model", "Model"),
    ("prompt_version", "Prompt version"),
    ("generated_at", "Generated"),
    ("latency_ms", "Latency (ms)"),
    ("input_tokens", "Input tokens"),
    ("output_tokens", "Output tokens"),
    ("estimated_cost", "Estimated cost"),
    ("redaction_summary", "Redacted before sending"),
)


def _rows(view: Mapping[str, Any]) -> list[tuple[str, str]]:
    rows = []
    for key, label in EXPORTED_FIELDS:
        value = view.get(key)
        if value in (None, "", []):
            continue
        rows.append((label, str(value)))
    return rows


def as_markdown(
    views: list[Mapping[str, Any]], *, evidence: str, generated_at: str
) -> str:
    """One Markdown document. Evidence first, then each PRISM view."""

    lines = [
        "# Atlas evidence, presented by PRISM",
        "",
        f"*Exported {generated_at}*",
        "",
        "## Atlas evidence (the source of truth)",
        "",
        "```",
        evidence.strip(),
        "```",
        "",
    ]
    for view in views:
        title = view.get("audience_label") or "PRISM view"
        if view.get("translated"):
            title = f"{title} — {view.get('language_label')}"
        lines += [f"## PRISM view — {title}", ""]
        if not view.get("ok"):
            lines += [
                "*PRISM could not generate this view. The Atlas evidence "
                "above is unchanged and complete.*",
                "",
            ]
            continue
        lines += [view.get("text", "").strip(), "", "### Generation metadata", ""]
        lines += [f"- **{label}:** {value}" for label, value in _rows(view)]
        lines += [""]
    lines += ["---", "", PROVENANCE_STATEMENT, ""]
    return "\n".join(lines)


def as_text(
    views: list[Mapping[str, Any]], *, evidence: str, generated_at: str
) -> str:
    """Plain text, for pasting into a ticket or an email."""

    rule = "=" * 70
    lines = [
        "ATLAS EVIDENCE, PRESENTED BY PRISM",
        f"Exported {generated_at}",
        rule,
        "ATLAS EVIDENCE (THE SOURCE OF TRUTH)",
        rule,
        evidence.strip(),
        "",
    ]
    for view in views:
        title = view.get("audience_label") or "PRISM view"
        if view.get("translated"):
            title = f"{title} - {view.get('language_label')}"
        lines += [rule, f"PRISM VIEW - {title}", rule]
        if not view.get("ok"):
            lines += [
                "PRISM could not generate this view. The Atlas evidence "
                "above is unchanged and complete.", "",
            ]
            continue
        lines += [view.get("text", "").strip(), "", "Generation metadata:"]
        lines += [f"  {label}: {value}" for label, value in _rows(view)]
        lines += [""]
    lines += [rule, PROVENANCE_STATEMENT, ""]
    return "\n".join(lines)


# -- PDF --------------------------------------------------------------------
#
# Written directly, with no dependency: PRISM added none to Atlas and an
# export format is a poor reason to start. This is a deliberately small
# PDF 1.4 writer — Helvetica, one page size, wrapped text — because the
# document it produces is a few paragraphs of prose and a metadata
# table, not a typeset report.

_PAGE_WIDTH, _PAGE_HEIGHT = 595, 842      # A4 in points
_MARGIN = 56
_LINE_HEIGHT = 14
_BODY_SIZE = 10
_HEAD_SIZE = 14
_MAX_CHARS = 92                            # ~fits the line at 10pt


def _escape_pdf(text: str) -> str:
    out = (
        text.replace("\\", r"\\").replace("(", r"\(").replace(")", r"\)")
    )
    # The base-14 fonts are Latin-1; anything else becomes "?" rather
    # than producing a corrupt document.
    return out.encode("latin-1", "replace").decode("latin-1")


def _wrap(text: str, width: int = _MAX_CHARS) -> list[str]:
    lines: list[str] = []
    for paragraph in text.splitlines():
        if not paragraph.strip():
            lines.append("")
            continue
        current = ""
        for word in paragraph.split():
            candidate = f"{current} {word}".strip()
            if len(candidate) <= width:
                current = candidate
            else:
                lines.append(current)
                current = word
        if current:
            lines.append(current)
    return lines


def _pdf_document(blocks: list[tuple[str, str]]) -> bytes:
    """Blocks of (style, text) where style is 'head' or 'body'."""

    pages: list[list[str]] = []
    stream: list[str] = []
    y = _PAGE_HEIGHT - _MARGIN

    def newline(size: int, text: str, bold: bool) -> None:
        nonlocal y, stream
        if y < _MARGIN + _LINE_HEIGHT:
            pages.append(stream)
            stream = []
            y = _PAGE_HEIGHT - _MARGIN
        font = "F2" if bold else "F1"
        stream.append(
            f"BT /{font} {size} Tf {_MARGIN} {y} Td ({_escape_pdf(text)}) Tj ET"
        )
        y -= _LINE_HEIGHT if size <= _BODY_SIZE else _LINE_HEIGHT + 6

    for style, text in blocks:
        if style == "head":
            y -= 6
            newline(_HEAD_SIZE, text, True)
        else:
            for line in _wrap(text):
                newline(_BODY_SIZE, line, False)
    pages.append(stream)

    objects: list[bytes] = []
    page_ids = [4 + index * 2 for index in range(len(pages))]
    kids = " ".join(f"{pid} 0 R" for pid in page_ids)
    objects.append(b"<< /Type /Catalog /Pages 2 0 R >>")
    objects.append(
        f"<< /Type /Pages /Kids [{kids}] /Count {len(pages)} >>".encode()
    )
    objects.append(
        b"<< /Font << /F1 << /Type /Font /Subtype /Type1 "
        b"/BaseFont /Helvetica >> /F2 << /Type /Font /Subtype /Type1 "
        b"/BaseFont /Helvetica-Bold >> >> >>"
    )
    for index, page_stream in enumerate(pages):
        content_id = page_ids[index] + 1
        objects.append(
            f"<< /Type /Page /Parent 2 0 R /Resources 3 0 R "
            f"/MediaBox [0 0 {_PAGE_WIDTH} {_PAGE_HEIGHT}] "
            f"/Contents {content_id} 0 R >>".encode()
        )
        body = "\n".join(page_stream).encode("latin-1", "replace")
        objects.append(
            b"<< /Length " + str(len(body)).encode() + b" >>\nstream\n"
            + body + b"\nendstream"
        )

    out = bytearray(b"%PDF-1.4\n")
    offsets = [0]
    for number, payload in enumerate(objects, start=1):
        offsets.append(len(out))
        out += f"{number} 0 obj\n".encode() + payload + b"\nendobj\n"
    xref_at = len(out)
    out += f"xref\n0 {len(objects) + 1}\n".encode()
    out += b"0000000000 65535 f \n"
    for offset in offsets[1:]:
        out += f"{offset:010d} 00000 n \n".encode()
    out += (
        f"trailer\n<< /Size {len(objects) + 1} /Root 1 0 R >>\n"
        f"startxref\n{xref_at}\n%%EOF\n"
    ).encode()
    return bytes(out)


def as_pdf(
    views: list[Mapping[str, Any]], *, evidence: str, generated_at: str
) -> bytes:
    blocks: list[tuple[str, str]] = [
        ("head", "Atlas evidence, presented by PRISM"),
        ("body", f"Exported {generated_at}"),
        ("head", "Atlas evidence (the source of truth)"),
        ("body", evidence.strip()),
    ]
    for view in views:
        title = view.get("audience_label") or "PRISM view"
        if view.get("translated"):
            title = f"{title} - {view.get('language_label')}"
        blocks.append(("head", f"PRISM view - {title}"))
        if not view.get("ok"):
            blocks.append((
                "body",
                "PRISM could not generate this view. The Atlas evidence "
                "above is unchanged and complete.",
            ))
            continue
        blocks.append(("body", view.get("text", "").strip()))
        blocks.append(("body", ""))
        for label, value in _rows(view):
            blocks.append(("body", f"{label}: {value}"))
    blocks.append(("head", "Provenance"))
    blocks.append(("body", PROVENANCE_STATEMENT))
    return _pdf_document(blocks)


# Base mimetypes only: the web layer appends the charset for text
# types, and declaring it here too produced "charset=utf-8;
# charset=utf-8" on the wire.
EXPORT_FORMATS = {
    "md": ("text/markdown", "prism-view.md"),
    "txt": ("text/plain", "prism-view.txt"),
    "pdf": ("application/pdf", "prism-view.pdf"),
}


def render(
    fmt: str, views: list[Mapping[str, Any]], *, evidence: str,
    generated_at: str,
) -> tuple[bytes, str, str]:
    """(payload, content type, filename) for one export format."""

    content_type, filename = EXPORT_FORMATS[fmt]
    if fmt == "pdf":
        return (
            as_pdf(views, evidence=evidence, generated_at=generated_at),
            content_type, filename,
        )
    text = (as_markdown if fmt == "md" else as_text)(
        views, evidence=evidence, generated_at=generated_at
    )
    return text.encode("utf-8"), content_type, filename
